name: Check PR changes

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Set up Go environment
        uses: actions/setup-go@v2.1.5
        with:
          go-version: 1.17

      - uses: actions/checkout@v2

      - name: Cache
        uses: actions/cache@v2.1.7
        with:
          path: ~/go/pkg/mod
          key: ${{ runner.os }}-build-${{ hashFiles('go.sum') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Build
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go build .

      - name: Test
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go test -v

      - name: Generate
        env:
          GOPROXY: "https://proxy.golang.org"
        run: go generate

      - name: Staticcheck
        env:
          GOPROXY: "https://proxy.golang.org"
        run: |
          go get -u honnef.co/go/tools/cmd/staticcheck
          staticcheck ./...

      - name: Collect changes
        uses: UnicornGlobal/has-changes-action@v1.0.11

      - name: Check if changes are present
        if: steps.changes.outputs.changed == 1
        uses: actions/github-script@v3
        with:
          script: |
            core.setFailed('The generated conversion list needs to be committed')